services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: vectorlog_postgres
    environment:
      POSTGRES_USER: vectorlog
      POSTGRES_PASSWORD: vectorlog
      POSTGRES_DB: vectorlogdb
    ports:
      - "5432:5432"
    volumes:
      - vectorlog_pgdata:/var/lib/postgresql/data
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vectorlog -d vectorlogdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  opensearch:
    image: opensearchproject/opensearch:2.13.0
    container_name: vectorlog_opensearch
    environment:
      - discovery.type=single-node
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=Admin_123!
      - plugins.security.disabled=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - vectorlog_osdata:/usr/share/opensearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:9200/_cluster/health || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 8

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.13.0
    container_name: vectorlog_dashboards
    ports:
      - "5601:5601"
    environment:
      - OPENSEARCH_HOSTS=http://opensearch:9200
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
    depends_on:
      opensearch:
        condition: service_healthy

volumes:
  vectorlog_pgdata:
  vectorlog_osdata:
